
	
	import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.statistics.HistogramDataset;
import org.jfree.data.xy.IntervalXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import project.Distribute;
import project.Generate;
import project.GenerateLoad;
import project.Method;
import sexpr.Parser;
import sexpr.Sexpr;

	/**
	 *
	 * @author abimbolaakinmeji
	 */
	
	@SuppressWarnings("serial")
	public class TestPanel extends javax.swing.JPanel {
	    ChartPanel chartPanel;

	    /**
	     * Creates new form NewJPanel
	     */
	    public TestPanel() {
	        initComponents();
	        createGraph();
	    }
	    
	  

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    private void initComponents() {

	        setLayout(new java.awt.GridBagLayout());
	    }                     


	                  

	  public final void createGraph() {
	        final IntervalXYDataset dataset = createDataset();
	        final JFreeChart chart = createChart(dataset);
	        chartPanel = new ChartPanel(chart);
	        chartPanel.setSize(400, 400);
	       // chartPanel.setLocation(40, 600);
	        this.add(chartPanel);
	    }
	    
	    private HistogramDataset createDataset() {
	    	GenerateLoad gl = new GenerateLoad();
	    	
	    	int[] loadDist = new int[100];
	    	for (int i = 0; i < loadDist.length; i++)
	    		loadDist[i] = (int)(30000*Generate.Normal(50, 30, i));
	    		//loadDist[i] = (int)(13000*Generate.Poisson(14, i));
	    	
	    	//gl.generate(loadDist);
	    	
	    	int[] rewardDist = new int[5];
	    	for (int i = 0; i < rewardDist.length; i++)
	    		rewardDist[i] = 2;
	    	
	    	int[] opentimeDist = new int[15];
	    	for (int i = 10; i < opentimeDist.length; i++)
	    		opentimeDist[i] = 2;
	    	
	    	int[] timepressureDist = new int[100];
	    	//for (int i = 0; i < 10; i++)
	    		//timepressureDist[i] = 2;
	    	timepressureDist[10] = 1;
	    	timepressureDist[20] = 1;
	    	
			
	    	gl.generate(loadDist, rewardDist, opentimeDist, timepressureDist);

	    	Parser p = new Parser();
			List<Sexpr> structure = null;
			try {
				//structure = p.parse("(spec_task (label root) (subtasks task1%50 task3%20 IdontExist useless...) ) (spec_task (label task1) (subtasks Method%75 task2) (deadline 100)) (spec_task (label task2) (subtasks Method%30) (world 2)) (spec_task (label task3) (subtasks Method%100)) (spec_task (label useless) (subtasks Method#1))");
				
				// figure out opening file
				// replace string with contents of opened file
				structure = p.parse("(spec_task (label root) (subtasks Method%50 tasksof2...%40 tasksof3...%60))  (spec_task (label tasksof2) (subtasks Method#2)) (spec_task (label tasksof3) (subtasks Method#3))");
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			Distribute.ToSexprs(structure, gl);
	    	
	    	// get generated structure as a string
	    	String finalStructure = "";
	    	for (Sexpr exp : structure) {
	    		finalStructure += (exp.toString());
	    	}
	    	//End On Save */
	    	
	    	System.out.println(finalStructure);
	    
	    	
	    	/*
	    	int value = 0;
	    	for (int i = 1; i <= 20; i++)
	    		gl.generateNextTimeStep((int)(300*Generate.Normal(10, 3, i)));
	    		//gl.generateNextTimeStep((int)(300*Generate.Laplace(10, 3, i)));
	    		//gl.generateNextTimeStep((int)(300*Generate.Exponential(1, 20, i)));
	    		//gl.generateNextTimeStep((int)(700 * Generate.Poisson(4, i)));
	    		//gl.generateNextTimeStep((value += (int)(700 * Generate.Poisson(10, i))));
	    	gl.generateNextTimeStep(0);*/
	    	
	    	double[] opentimeActual = new double[gl.generated.size()];
	    	int sumOpenTime = 0;
			for (int i = 0; i < opentimeDist.length; i++)
				sumOpenTime += opentimeDist[i];
			int countO = 0;
			for (int i = 0; i < opentimeDist.length; i++)
				for (int j = 0; j < opentimeDist[i] * opentimeActual.length / sumOpenTime; j++)
					opentimeActual[countO++] = i;
	    	
	       HistogramDataset dataset = new HistogramDataset();
	       //dataset.addSeries("Load", loadDist,loadDist.length+1,0,loadDist.length);
	       //dataset.addSeries("Actual Load", gl.loadhistogram(),loadDist.length+1,0,loadDist.length);
	       //dataset.addSeries("Open Time", gl.opentimehistogram(), opentimeDist.length+1,0,opentimeDist.length);
	       //dataset.addSeries("Actual Open Time", opentimeActual,opentimeDist.length+1,0,opentimeDist.length);
	       dataset.addSeries("Time Pressure", gl.timePressurehist(), timepressureDist.length+1,0,timepressureDist.length);
	       dataset.addSeries("Actual Time Pressure", gl.actualTimePressureHist(),timepressureDist.length+1,0,timepressureDist.length);
	       //dataset.addSeries("Reward", gl.rewardhistogram(), rewardDist.length+1,0,rewardDist.length);
	       //dataset.addSeries("Actual Reward", gl.actualRewardHist(),rewardDist.length+1,0,rewardDist.length);
	       
	       return dataset;
	        
	    }
	    
	    private JFreeChart createChart(final IntervalXYDataset dataset) {

			final JFreeChart chart;
	        chart = ChartFactory.createHistogram(
	                "Histogram Demo",      // chart title
	                "Session",                      // x axis label
	                "Value",                      // y axis label
	                dataset,                  // data
	                PlotOrientation.VERTICAL,
	                true,                     // include legend
	                true,                     // tooltips
	                false                     // urls
	        );

			// NOW DO SOME OPTIONAL CUSTOMISATION OF THE CHART...
			chart.setBackgroundPaint(Color.white);

			chart.setBackgroundPaint(new Color(230,230,230));
	                 XYPlot xyplot = (XYPlot)chart.getPlot();
	                 xyplot.setForegroundAlpha(0.7F);
	                 xyplot.setBackgroundPaint(Color.WHITE);
	                 xyplot.setDomainGridlinePaint(new Color(150,150,150));
	                 xyplot.setRangeGridlinePaint(new Color(150,150,150));
	                 XYBarRenderer xybarrenderer = (XYBarRenderer)xyplot.getRenderer();
	                 xybarrenderer.setShadowVisible(false);
	                 xybarrenderer.setBarPainter(new StandardXYBarPainter()); 
//	    xybarrenderer.setDrawBarOutline(false);
			return chart;
		}



	}





